#!/usr/bin/env bash
source /etc/bashrc

#export ROCKSDBALLOWED=1

if [[ "$1" == "--local" || "$1" == "--coston" || "$1" == "--flare-coston1" || "$1" == "--songbird" || "$1" == "--songbird-validator" || "$1" == "--flare-observer" || "$1" == "--flare-validator" || "$1" == "--flare-coston2" ]]; then
  export FLARE_HOME="/home/flareuser/go-flare"
  export FLARE_BIND_ADDRESS="${FLARE_BIND_ADDRESS:-0.0.0.0}"

  cd $FLARE_HOME || exit 2

  if [[ -d "avalanchego" ]]; then
    export FLARE_BIN_PREFIX=/avalanchego
    export FLARE_BIN="$FLARE_HOME""$FLARE_BIN_PREFIX"/build/avalanchego
  else
    exit 3
  fi

  sed -i 's#/usr/local/go/bin#/usr/local/go-1.21.8/bin#' $HOME/.bashrc
  sed -i 's#/home/go$#/home/go-1.21.8#' $HOME/.bashrc
  source $HOME/.bashrc
fi

if [[ -z "$FLARE_ALLOWED_HOSTS" ]]; then
  export FLARE_ALLOWED_HOSTS="localhost"
fi

if [[ -n "$FLARE_BIND_ADDRESS" ]]; then
  export ETH0_IP="$FLARE_BIND_ADDRESS"

  if [[ "$FLARE_BIND_ADDRESS" == "0.0.0.0" ]]; then
    export FLARE_ALLOWED_HOSTS="*"
  fi
else
  export ETH0_IP="$( ifconfig eth0 | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1 )"
fi

if [[ "$1" == "--coston" || "$1" == "--flare-coston1" ]]; then
  "$FLARE_BIN" --data-dir=/home/flareuser/.flare --network-id=coston \
    --bootstrap-ips="$( curl -m 10 -sX POST \
      --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeIP" }' \
      -H 'content-type:application/json;' https://coston.flare.network/ext/info \
      | jq -r ".result.ip" )" \
    --bootstrap-ids="$( curl -m 10 -sX POST \
      --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeID" }' \
      -H 'content-type:application/json;' https://coston.flare.network/ext/info \
      | jq -r ".result.nodeID" )" \
    --http-allowed-hosts="$FLARE_ALLOWED_HOSTS" \
    --http-host="$ETH0_IP" >/dev/null 2>&1 &
elif [[ "$1" == "--songbird" || "$1" == "--songbird-validator" ]]; then
  "$FLARE_BIN" --data-dir=/home/flareuser/.flare --network-id=songbird \
  --bootstrap-ips="$( curl -m 10 -sX POST \
    --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeIP" }' \
    -H 'content-type:application/json;' https://songbird.flare.network/ext/info \
    | jq -r ".result.ip" )" \
  --bootstrap-ids="$( curl -m 10 -sX POST \
    --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeID" }' \
    -H 'content-type:application/json;' https://songbird.flare.network/ext/info \
    | jq -r ".result.nodeID" )" \
  --http-allowed-hosts="$FLARE_ALLOWED_HOSTS" \
  --http-host="$ETH0_IP" >/dev/null 2>&1 &

  sleep 10
elif [[ "$1" == "--flare-observer" || "$1" == "--flare-validator" ]]; then
  "$FLARE_BIN" --data-dir=/home/flareuser/.flare --network-id=flare \
  --bootstrap-ips="$(curl -m 10 -sX POST \
    --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeIP" }' \
    -H 'content-type:application/json;' https://flare.flare.network/ext/info \
    | jq -r ".result.ip")" \
  --bootstrap-ids="$(curl -m 10 -sX POST \
    --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeID" }' \
    -H 'content-type:application/json;' https://flare.flare.network/ext/info \
    | jq -r ".result.nodeID")" \
  --http-allowed-hosts="$FLARE_ALLOWED_HOSTS" \
  --http-host="$ETH0_IP" >/dev/null 2>&1 &

  sleep 10
else
  "$FLARE_BIN" --data-dir=/home/flareuser/.flare --network-id=costwo \
  --bootstrap-ips="$(curl -m 10 -sX POST \
    --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeIP" }' \
    -H 'content-type:application/json;' https://coston2.flare.network/ext/info \
    | jq -r ".result.ip")" \
  --bootstrap-ids="$(curl -m 10 -sX POST \
    --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeID" }' \
    -H 'content-type:application/json;' https://coston2.flare.network/ext/info \
    | jq -r ".result.nodeID")" \
  --http-allowed-hosts="$FLARE_ALLOWED_HOSTS" \
  --http-host="$ETH0_IP" >/dev/null 2>&1 &

  sleep 10
fi

runall </dev/null >/dev/null 2>&1
