#!/usr/bin/env bash
# Cron: */10 * * * * bash --login -c '/home/flareuser/bin/sgbcheckcmd > /home/flareuser/log/check.log 2>&1'

export GOPATH=/home/go

sgbcheckout=$( node /home/flareuser/bin/sgbcheck.js )

if [[ "$sgbcheckout" == 1 ]]; then
    sgbpid=$( lsof -t -i:9650 )

    if [[ ! -z "$sgbpid" ]]; then
      kill $sgbpid
      sleep 10
      /home/flareuser/flare/build/flare --network-id=songbird --bootstrap-ips="$( curl -m 10 -sX POST --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeIP" }' -H 'content-type:application/json;' https://songbird.flare.network/ext/info | jq -r ".result.ip" )" --bootstrap-ids="$( curl -m 10 -sX POST --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeID" }' -H 'content-type:application/json;' https://songbird.flare.network/ext/info | jq -r ".result.nodeID" )" --http-host="0.0.0.0" >/dev/null 2>&1 &
    else
      rm -rf /home/flareuser/.flare/db/*
      rm -rf /home/flareuser/.flare/logs/*
      /home/flareuser/flare/build/flare --network-id=songbird --bootstrap-ips="$( curl -m 10 -sX POST --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeIP" }' -H 'content-type:application/json;' https://songbird.flare.network/ext/info | jq -r ".result.ip" )" --bootstrap-ids="$( curl -m 10 -sX POST --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeID" }' -H 'content-type:application/json;' https://songbird.flare.network/ext/info | jq -r ".result.nodeID" )" --http-host="0.0.0.0" >/dev/null 2>&1 &
    fi
fi
