#!/usr/bin/env bash
# Cron: */2 * * * * bash --login -c '/home/flareuser/bin/sgbchecklogcmd > /home/flareuser/log/checklog.log 2>&1'
# main.log
# 01-17|15:04 .* network layer is unhealthy

export GOPATH=/home/go

if command -v lsof > /dev/null 2>&1; then
  e=
  for (( i = 2; i > 0; i-- )) ; do
      e='-e /'`date +\%m-\%d`\|`date  +\%R -d "-$i min"`'/p '$e
  done

  sed -n $e /home/flareuser/.flare/logs/main.log > tmp.log
  #sed -n $e main.log > tmp.log

  if grep -q "network layer is unhealthy" tmp.log; then
    sgbpid=$( lsof -t -i:9650 )

    if [[ ! -z "$sgbpid" ]]; then
      kill $sgbpid
      sleep 10
      /home/flareuser/flare/build/flare --network-id=songbird --bootstrap-ips="$( curl -m 10 -sX POST --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeIP" }' -H 'content-type:application/json;' https://songbird.flare.network/ext/info | jq -r ".result.ip" )" --bootstrap-ids="$( curl -m 10 -sX POST --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeID" }' -H 'content-type:application/json;' https://songbird.flare.network/ext/info | jq -r ".result.nodeID" )" --http-host="0.0.0.0" >/dev/null 2>&1 &
    else
      /home/flareuser/flare/build/flare --network-id=songbird --bootstrap-ips="$( curl -m 10 -sX POST --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeIP" }' -H 'content-type:application/json;' https://songbird.flare.network/ext/info | jq -r ".result.ip" )" --bootstrap-ids="$( curl -m 10 -sX POST --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeID" }' -H 'content-type:application/json;' https://songbird.flare.network/ext/info | jq -r ".result.nodeID" )" --http-host="0.0.0.0" >/dev/null 2>&1 &
      sleep 60
      sgbpid=$( lsof -t -i:9650 )
      if [[ -z "$sgbpid" ]]; then
        rm -rf /home/flareuser/.flare/db/*
        rm -rf /home/flareuser/.flare/logs/*
        /home/flareuser/flare/build/flaree --network-id=songbird --bootstrap-ips="$( curl -m 10 -sX POST --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeIP" }' -H 'content-type:application/json;' https://songbird.flare.network/ext/info | jq -r ".result.ip" )" --bootstrap-ids="$( curl -m 10 -sX POST --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeID" }' -H 'content-type:application/json;' https://songbird.flare.network/ext/info | jq -r ".result.nodeID" )" --http-host="0.0.0.0" >/dev/null 2>&1 &
      fi
    fi
  fi

  rm -f tmp.log
else
  echo "You must install the 'lsof' package to run this script."
  exit 1
fi
